config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"

  get '/posts', to: 'posts#index'
  get '/comments', to: 'comments#index'
  resources :friendables, only: [:create, :update, :destroy]
  root to: "welcome#index"
  resources :users do
    resources :posts do
      resources :comments
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/friendable.rb
class Friendable < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, uniqueness: true
  validates :avatar,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ }
  if Rails.env.production?
  has_attached_file :avatar, styles: { large: "670x520", medium: "300x220>", thumb: "150x150#" },
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :path => ":style/:id_:filename"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  else
    has_attached_file :avatar,
      :styles => {:medium => "200x", :thumb => "100x100>" }, :default_url => "missing.png"
  end
  has_many :posts
  has_many :comments
  has_many :friendables
  has_many :passive_friendships, :class_name => "Friendable", :foreign_key => "friend_id"

  has_many :active_friends, -> { where(friendables: { accepted: true}) }, :through => :friendables, :source => :friend
  has_many :passive_friends, -> { where(friendables: { accepted: true}) }, :through => :passive_friendships, :source => :user
  has_many :pending_friends, -> { where(friendables: { accepted: false}) }, :through => :friendables, :source => :friend
  has_many :requested_friendships, -> { where(friendables: { accepted: false}) }, :through => :passive_friendships, :source => :user


  def friends
    active_friends | passive_friends
  end

  def self.confirm(email_param, password_param)
    user = User.find_by_email(email_param)
    user.authenticate(password_param)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private


  def current_user
    @current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
  end

  def require_login
    if !current_user
      redirect_to root_path #halt's request cycle
    end
  end

  helper_method :current_user #make it available in views
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all 
    render json: @comments
  end

  def new
    @comment = Comment.new
    @user = current_user
  end

  def create
    @comment = Comment.new(comment_params)
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    if @comment.save
      @user.comments << @comment
      @post.comments << @comment
      redirect_to @user
    else
      render :new
    end
  end
  
  def show
    @comment = Comment.find(params[:id])
    user_id = @comment.user_id
    @user = User.find(user_id)
  end

  def edit
    @current_user = current_user
    if @current_user.id = params[:user_id]
      @comment = Comment.find(params[:id])
      puts @comment
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to comment_path(@comment)
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to user_path
  end

  private
    def find_user
      @user = User.find(params[:user_id])
    end

    def find_comment
      @comment = Comment.find(params[:id])
    end
    
    def comment_params 
      params.require(:comment).permit(:body)
    end
end

app/controllers/friendables_controller.rb
class FriendablesController < ApplicationController
  def create
    @friendables = current_user.friendables.build(:friend_id => params[:friend_id], accepted: "false")
    if @friendables.save
      flash[:notice] = "Friend Requested."
      redirect_to user_path(@friendables.friend_id)
    else
      flash[:notice] = "Unable to request friendship."
      redirect_to :back
    end
  end

  def update
    @friendable = Friendable.where(user_id: current_user.id, friend_id: params[:id].to_i)
    @friendable.first.update(accepted: true)
      if @friendable.first.save
        redirect_to user_path(current_user.id), :notice => "Succesfully confirmed friend!"
      else
        redirect_to user_path(current_user.id), :notice => "Sorry! Could not confirm friend!"
      end
  end

  def destroy
    @friendable = Friendable.where(friend_id: [current_user, params[:id]]).where(user_id: [current_user, params[:id]]).last
    @friendable.destroy
    flash[:notice] = "Removed friendable."
    redirect_to :back
  end

  private
  def friendable_params
    params.require(:friendable).permit(:accepted)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all 
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    @post = Post.new(post_params)
    @user = User.find(params[:user_id])
    if @post.save
      @user.posts << @post
      redirect_to @user
    else
      render :new
    end
  end
  
  def show
    @post = Post.find(params[:id])
    user_id = @post.user_id
    @user = User.find(user_id)
  end

  def edit
    @current_user = current_user
    if @current_user.id = params[:user_id]
      @post = Post.find(params[:id])
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete
    redirect_to user_path
  end

  private
    def find_user
      @user = User.find(params[:user_id])
    end

    def find_post
      @post = Post.find(params[:id])
    end
    
    def post_params 
      params.require(:post).permit(:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to current_user if current_user
  end

  def create
    user = User.confirm(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
    render json: @user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user 
    else
      redirect_to  new_user_path
    end
  end

  def show
    user_id = params[:id]
    if current_user.id == user_id.to_i
      @user = User.find(current_user.id)
      @posts = []
      @user.posts.each do |t|
        @posts.push(t)
      end
    else
      @user = User.find(user_id)
    end 
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :languages, :avatar)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_controller_helper.rb
module UserControllerHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/friendables/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendables/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/friendables/update.html.erb
<h1>Friendships#update</h1>
<p>Find me in app/views/friendships/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <%= yield %>
  
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Home", root_path %></div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li></li>
        <% if current_user %>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
          </ul>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Logout", sessions_path, method: :delete %> 
		<% else %>
  			<li><%= link_to "Signup", new_user_path %></li>
				<li><%= link_to "Login", login_path %><li>
<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<div class="container">
  <div class="row row-wrap">
    <% @posts.each do |p| %>
      <div class="col-xs-4 col-sm-4 col-md-4">
        <div class="posts_index">
          <p><%= p.body %></p>
          <small><%= image_tag User.where(id: p.user_id).first.avatar.url(:thumb) %><%= link_to User.where(id: p.user_id).first.name, user_path(p.user_id) %> </small>
          </p>
        </div>
      </div>
    <% end %>
  </div>

app/views/posts/new.html.erb
<% if current_user %>
<%= form_for [@user, @post]  do |f| %>
  <%= f.label "title" %>
  <%= f.text_area :body, class: "form-control" %><br>
  <%= f.submit :submit %>
<% end %>
<% else %>
  <h1>Please Login</h1>
<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<%= form_for @user, :html => { :multipart => true } do |f| %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.email_field :email, class: "form-control" %>
  <%= f.text_field :languages, class: "form-control" %>
  <%= f.file_field :avatar, class: "form-control" %>
  <%= f.hidden_field :password, class: "form-control" %>
  <%= f.hidden_field :password_confirmation, class: "form_control" %>
  <%= f.submit "Save Changes" %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>SIGNUP!</h1>

<% if @user.errors.any? %>
  <div>
    <ul>
      <% @article.errors.full_messages.each do |msg| %> 
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for(@user) do |f| %>
  Name: <%= f.text_field :name, class: "form-control" %>
  Email: <%= f.text_field :email, class: "form-control"  %>
  Password: <%= f.password_field :password, class: "form-control"  %>
  Password Confirmation: <%= f.password_field :password_confirmation, class: "form-control"  %>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <h1 class="jumbotron">
    Hello <%= @user.name %>
    <%= image_tag @user.avatar.url(:thumb) %>
  </h1>
  <div class="row">
    <div class="col-md-3">
      <% if current_user == @user %>
        <div class="friends_list">
          <% current_user.friends.each do |t| %>
            <%= image_tag t.avatar.url(:thumb) %>
            <p><%= link_to t.name, user_path(t.id) %></p>
          <% end %>
        </div>
        <div class="pending_friends">
          <% current_user.pending_friends.each do |p| %>
            <p>Pending friend: <%= p.name %>
            <%= link_to "Confirm friend?", friendable_path(p.id), :method => "put" %>
            </p>
          <% end %>
        </div>
      <% end %>

        <div class="new_friend">
          <% unless current_user == @user %>
            <% if current_user.friends.all? {|t| t.id != @user.id} %>
              <%= link_to "Add Friend", friendables_path(:friend_id => @user), :method => :post %>
            <% else %>
              Already friends!
            <% end %>
          <% end %>
        </div>
    </div>
    <% if current_user == @user %>
      <%= form_for :post, url: "/users/#{current_user.id}/posts" do |post| %>
        <%= post.text_area :body, placeholder: "New Post" %>
        <%= post.submit "Submit" %>
      <% end %>
    <% end %>
    <% if @posts %>
      <% @posts.each do |p| %>
        <div class="user_posts">
          <%= p.body %>
          <%= form_for :comment, url: "/users/#{current_user.id}/posts/#{p.id}/comments" do |t| %>
            <%= t.text_field :body, placeholder: "New comment" %>
            <%= t.submit "Submit" %>
          <% end %>
          <% p.comments.each do |c| %>
            <div class="post_comments">
              <%= c.body %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Codebook</h1>
  <h3>Creating better coders through collaboration</h3>
</div>